remote_theme: pmarsceill/just-the-docs
# color_scheme: dark
baseurl: /doc-bcx-validation
search_enabled: true
title: bcx-validation
aux_links:
  "\"bcx-validation\" on GitHub":
    - "//github.com/buttonwoodcx/bcx-validation"
